import Foundation
import NeutrinoCore

// MARK: - RecoveryKit

/// The recovery kit — the identity keyring on paper.
///
/// A port of `web/packages/e2e-crypto/src/recoveryKit.ts`, and it has to stay one: a kit written
/// down from this device is typed into the web app to restore the account, so the frame and the
/// alphabet are a wire format, not a presentation choice. `RecoveryKitTests` pins both against
/// strings generated by the web implementation.
///
/// One keyring per account, not per app: a kit exported from Sheets restores Docs, because the
/// identity it carries is the account's rather than any one editor's.
///
/// The frame is compact binary in Crockford base32 rather than JSON, because a person copies this
/// by hand: the alphabet has no I, L, O or U, so the common misreadings cannot happen at all.
/// Timestamps are deliberately absent — they are display metadata, not key material, and a restore
/// stamps its own.
///
/// With no server copy of the active secret key, this is the only thing that survives losing every
/// enrolled device. Nothing here can soften that, and no support process can either.
public enum RecoveryKit {

    // MARK: - Entry

    /// One keyring version, as the kit carries it.
    public struct Entry: Equatable {
        /// 1-based, matching `user_public_keys.version` on the server.
        public let version: Int
        /// The raw 32-byte Curve25519 secret key.
        public let secretKey: Data
        /// Nil while this is the active entry.
        public let isRetired: Bool

        public init(version: Int, secretKey: Data, isRetired: Bool = false) {
            self.version = version
            self.secretKey = secretKey
            self.isRetired = isRetired
        }
    }

    // MARK: - Format

    /// Crockford base32 — no I, L, O or U.
    ///
    /// Internal rather than private so `looksLikeKit`, in the keyring bridge beside this, can ask
    /// whether a string is even in the alphabet without decoding it.
    static let alphabet = Array("0123456789ABCDEFGHJKMNPQRSTVWXYZ")
    private static let groupSize = 4
    private static let groupsPerLine = 8

    private static let magic: UInt8 = 0x4E // 'N'
    private static let formatVersion: UInt8 = 1
    private static let flagRetired: UInt8 = 0x01
    private static let secretKeyBytes = 32
    private static let entryBytes = 2 /* version */ + secretKeyBytes + 1 /* flags */

    // MARK: - Export

    /// Render `entries` as the printable kit: groups of four, eight to a line.
    ///
    /// The whole keyring goes in, not just the active key — a file sealed to version 1 needs
    /// version 1, and a kit that restored only the newest key would come back to a library it
    /// cannot open.
    public static func export(entries: [Entry]) -> String {
        let encoded = base32(encodeFrame(entries))

        var groups: [String] = []
        var index = encoded.startIndex
        while index < encoded.endIndex {
            let end = encoded.index(index, offsetBy: groupSize, limitedBy: encoded.endIndex)
                ?? encoded.endIndex
            groups.append(String(encoded[index..<end]))
            index = end
        }

        return stride(from: 0, to: groups.count, by: groupsPerLine)
            .map { groups[$0..<min($0 + groupsPerLine, groups.count)].joined(separator: "-") }
            .joined(separator: "\n")
    }

    // MARK: - Import

    /// Rebuild a keyring from a printed kit.
    ///
    /// Everything here came off paper, so none of it is trusted: a wrong length, a duplicate
    /// version or a kit that does not name exactly one active key are all rejected now, rather than
    /// surfacing later as files that mysteriously will not open.
    ///
    /// No account is named — the kit holds key material only, and binding it to a user is the
    /// caller's business (`KeyProvisioningService.restoreFromRecoveryKit`).
    public static func `import`(_ text: String) throws -> [Entry] {
        let normalized = normalize(text)
        guard !normalized.isEmpty else { throw RecoveryKitError.empty }
        return try decodeFrame(try unbase32(normalized))
    }

    /// Fold the common misreadings back before decoding.
    ///
    /// Crockford's whole point is that these characters are unambiguous *if* you map them: someone
    /// copying off paper writes O for 0 and l for 1 regardless of what the alphabet says.
    public static func normalize(_ text: String) -> String {
        var out = ""
        for character in text.uppercased() {
            switch character {
            case " ", "\t", "\n", "\r", "-": continue
            case "O":                        out.append("0")
            case "I", "L":                   out.append("1")
            case "U":                        out.append("V")
            default:                         out.append(character)
            }
        }
        return out
    }

    // MARK: - Framing

    private static func encodeFrame(_ entries: [Entry]) -> [UInt8] {
        var out: [UInt8] = [magic, formatVersion, UInt8(entries.count)]
        for entry in entries {
            out.append(UInt8((entry.version >> 8) & 0xFF))
            out.append(UInt8(entry.version & 0xFF))
            out.append(contentsOf: entry.secretKey)
            out.append(entry.isRetired ? flagRetired : 0)
        }
        return out
    }

    private static func decodeFrame(_ bytes: [UInt8]) throws -> [Entry] {
        guard bytes.count >= 3, bytes[0] == magic else { throw RecoveryKitError.notARecoveryKit }
        guard bytes[1] == formatVersion else {
            throw RecoveryKitError.unsupportedVersion(Int(bytes[1]))
        }

        let count = Int(bytes[2])
        // A truncated kit is the likely outcome of copying by hand, so say that rather than letting
        // a short read produce a subtly wrong key.
        guard count > 0, bytes.count >= 3 + count * entryBytes else {
            throw RecoveryKitError.incomplete
        }

        var entries: [Entry] = []
        var offset = 3
        for _ in 0..<count {
            let version = (Int(bytes[offset]) << 8) | Int(bytes[offset + 1])
            guard version >= 1 else { throw RecoveryKitError.damaged }
            let secretKey = Data(bytes[(offset + 2)..<(offset + 2 + secretKeyBytes)])
            let retired = (bytes[offset + 2 + secretKeyBytes] & flagRetired) != 0
            entries.append(Entry(version: version, secretKey: secretKey, isRetired: retired))
            offset += entryBytes
        }

        // Both checks the web applies to the same bytes on its side (`deserializeKeyring`): a
        // duplicate version has no meaning, and a keyring without exactly one active key cannot say
        // what new files should be sealed to.
        guard Set(entries.map(\.version)).count == entries.count else {
            throw RecoveryKitError.damaged
        }
        guard entries.filter({ !$0.isRetired }).count == 1 else {
            throw RecoveryKitError.noSingleActiveKey
        }

        return entries.sorted { $0.version < $1.version }
    }

    // MARK: - base32

    private static func base32(_ bytes: [UInt8]) -> String {
        var bits = 0
        var value = 0
        var out = ""
        for byte in bytes {
            value = (value << 8) | Int(byte)
            bits += 8
            while bits >= 5 {
                out.append(alphabet[(value >> (bits - 5)) & 31])
                bits -= 5
            }
        }
        // The trailing partial group is padded with zero bits rather than dropped — those bits are
        // key material.
        if bits > 0 {
            out.append(alphabet[(value << (5 - bits)) & 31])
        }
        return out
    }

    /// The inverse. Trailing bits that do not complete a byte are the encoder's padding and are
    /// dropped, exactly as the web decoder drops them.
    private static func unbase32(_ text: String) throws -> [UInt8] {
        var bits = 0
        var value = 0
        var out: [UInt8] = []
        for character in text {
            guard let index = alphabet.firstIndex(of: character) else {
                throw RecoveryKitError.unexpectedCharacter(String(character))
            }
            value = (value << 5) | index
            bits += 5
            if bits >= 8 {
                out.append(UInt8((value >> (bits - 8)) & 0xFF))
                bits -= 8
            }
        }
        return out
    }
}

// MARK: - Errors

public enum RecoveryKitError: LocalizedError, Equatable {
    case empty
    case unexpectedCharacter(String)
    case notARecoveryKit
    case unsupportedVersion(Int)
    case incomplete
    case noSingleActiveKey
    case damaged

    public var errorDescription: String? {
        switch self {
        case .empty:
            return "Enter your recovery kit."
        case .unexpectedCharacter(let character):
            return "Your recovery kit contains an unexpected character: \u{201C}\(character)\u{201D}."
        case .notARecoveryKit:
            return "This does not look like a Neutrino recovery kit."
        case .unsupportedVersion(let version):
            return "This recovery kit is version \(version), which this app does not understand. "
                 + "Update \(NeutrinoApp.current.displayName) and try again."
        case .incomplete:
            return "Your recovery kit is incomplete — some characters are missing."
        case .noSingleActiveKey:
            return "This recovery kit is damaged — it does not name exactly one active key."
        case .damaged:
            return "This recovery kit is damaged."
        }
    }
}
