#!/usr/bin/env node
//
// Writes Tests/NeutrinoCryptoTests/Fixtures/place_envelope_vectors.json: saved-place envelopes
// sealed by the web's own crypto (`encryptFileKey` and `encryptMetadata` in the sibling `neutrino`
// checkout's web/packages/e2e-crypto/src/crypto.ts), so `PlaceEnvelopeTests` proves NeutrinoCrypto
// opens what the web writes, not what someone believes it writes. The envelope is specified in
// neutrino/agent_docs/end-to-end-encryption.md.
//
//   scripts/generate_place_envelope_vectors.mjs
//
// Runs crypto.ts under Node's type stripping (Node 23.5+, for `registerHooks`). Sealing is
// randomized, so each run writes different ciphertext for the same places; commit the JSON only
// when the cases change, and copy it to the web's
// neutrino/web/packages/e2e-crypto/src/__tests__/fixtures/ so both sides test the same bytes.

import { createRequire, registerHooks } from 'node:module';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..');
const cryptoTs = join(repo, '..', 'neutrino', 'web', 'packages', 'e2e-crypto', 'src', 'crypto.ts');
const out = join(repo, 'Tests', 'NeutrinoCryptoTests', 'Fixtures', 'place_envelope_vectors.json');

// libsodium-wrappers 0.7.16's ESM entry imports a file its package doesn't ship, so plain Node
// can't load it (bundlers and Vitest never notice). Its CommonJS build is the same library.
const sodiumCjs = createRequire(cryptoTs).resolve('libsodium-wrappers');
registerHooks({
  resolve(specifier, context, next) {
    if (specifier === 'libsodium-wrappers') return { url: pathToFileURL(sodiumCjs).href, shortCircuit: true };
    return next(specifier, context);
  },
});

const c = await import(pathToFileURL(cryptoTs).href);
await c.initSodium();

// One keypair per key version, so a case can be sealed to a retired key.
const keys = { 1: c.generateKeyPair(), 2: c.generateKeyPair() };

function seal(payload, keyVersion) {
  const dek = c.generateFileKey();
  return JSON.stringify({
    v: 1,
    keyVersion,
    key: c.encryptFileKey(dek, keys[keyVersion].publicKey),
    data: c.encryptMetadata(payload, dek),
  });
}

const cases = [
  { name: 'saved place', keyVersion: 2, payload: { name: 'Home', lat: 51.501364, lng: -0.14189, radiusM: 150 } },
  { name: 'non-ASCII name', keyVersion: 2, payload: { name: 'Café Zoë — 東京', lat: 35.681236, lng: 139.767125, radiusM: 100 } },
  { name: 'retired key version', keyVersion: 1, payload: { name: 'Old office', lat: -33.865143, lng: 151.2099, radiusM: 2000 } },
  {
    name: 'unknown payload fields are ignored', keyVersion: 2,
    payload: { name: 'Gym', lat: 40.7128, lng: -74.006, radiusM: 300, icon: 'dumbbell' },
    expected: { name: 'Gym', lat: 40.7128, lng: -74.006, radiusM: 300 },
  },
];

const vectors = {
  comment: 'Generated by scripts/generate_place_envelope_vectors.mjs from the web e2e-crypto. Do not edit.',
  keys: Object.fromEntries(Object.entries(keys).map(([version, kp]) => [version, {
    publicKey: c.toBase64url(kp.publicKey),
    secretKey: c.toBase64url(kp.secretKey),
  }])),
  cases: cases.map(({ name, keyVersion, payload, expected }) => ({
    name,
    keyVersion,
    encryptedPayload: seal(payload, keyVersion),
    expected: expected ?? payload,
  })),
  rejected: [
    { name: 'future envelope version', encryptedPayload: JSON.stringify({ v: 2, keyVersion: 2, key: 'x', data: 'y' }), error: 'unsupportedVersion' },
    { name: 'not JSON', encryptedPayload: 'djE6bm90LWpzb24', error: 'malformed' },
    { name: 'missing version', encryptedPayload: JSON.stringify({ keyVersion: 2, key: 'x', data: 'y' }), error: 'malformed' },
  ],
};

writeFileSync(out, JSON.stringify(vectors, null, 2) + '\n');
console.log(`Wrote ${vectors.cases.length} cases to Tests/NeutrinoCryptoTests/Fixtures/place_envelope_vectors.json`);
